import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";
import { FiArrowRight } from "react-icons/fi";
import ProductCard from "../components/Menu/ProductCard";

const inter = Inter({ subsets: ["latin"] });

const products = [
  {
    name: "INEOM",
    subtitle:
      "Integrated asset management solutions that covers complete asset lifecycle: planning, procuring, operating, and dismantling.",
    imgUrl: "Product - INEOM.svg",
  },
  {
    name: "CHRONO",
    subtitle:
      "Procces EMS configuration and performance export file and provides consolidated data and analytical dashboard of network parameters.",
    imgUrl: "Product - CHRONO.svg",
  },
  {
    name: "ACTO",
    subtitle:
      "Consolidated ticketing system for all activities inside organizations. KPI calculations to ensure every stakeholder performs as expected.",
    imgUrl: "Product - ACTO.svg",
  },
  {
    name: "ENGGANO",
    subtitle:
      "Low code and integrated software development solutions for enterprises: bussiness procces, source code repository, and application deployment.",
    imgUrl: "Product - ENGGANO.svg",
  },
  {
    name: "VIXMO",
    subtitle:
      "AI and automation platform focused in autonomous vehicle technology.",
    imgUrl: "Product - VIXMO.svg",
  },
  {
    name: "OPTIMO",
    subtitle:
      "Enhancing customer experiences by processing layer-3 radio resource control data and provides further action recommendations.",
    imgUrl: "Product - OPTIMO.svg",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Mitra Informatika | Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          backgroundImage:
            "linear-gradient(90deg, rgba(0,0,0,1) 1.25%, rgba(43,44,49,1) 100.83%)",
        }}
        className="-mx-[80px] px-[80px] min-h-[80vh] pt-[10vh] bg-cover bg-center "
      >
        <section className="mt-24">
          <div className="flex justify-between items-start">
            <h1 className="w-1/2 text-6xl font-bold text-white relative z-10">
              INEOM Enterprise Asset Management for Telco
            </h1>
            <div className="w-1/2 text-xl text-white pl-20">
              <p className="relative z-10">
                <strong>We helps network service provider</strong> to achieve
                higher return of investment (ROI) in day-to-day operations by
                using our asset management, workforce management, and integrated
                ticketing solutions.
              </p>
              <Link
                href=""
                className="rounded-[4px] mt-6 w-fit bg-accent text-white font-semibold px-5 py-3 relative z-10 group flex items-center"
              >
                <div className="transition-all duration-200 mr-2 group-hover:mr-4">
                  Learn more
                </div>
                <FiArrowRight className="text-xl font-bold" />
              </Link>
            </div>
          </div>
          <img
            src="/home/Hero Banner.png"
            alt=""
            className="-mb-56 mt-20 relative z-10"
          />
        </section>

        <section className="bg-white px-[80px] -mx-[80px] pb-24 pt-[328px] mb-[170px]">
          <div className="flex items-start atpidarp space-x-[194px]">
            <p className="text-accent text-sm font-medium">OUR PRODUCT</p>
            <div className="border-accent max-w-[600px]">
              <h3 className="pb-10 text-black text-4xl font-semibold">
                “System must be built with philosophy”
              </h3>
              <div className="bg-accent max-w-[440px] h-[2px]"></div>
            </div>
          </div>
          <div className="mt-16">
            <div className="mt-3 grid grid-cols-3 gap-x-8 gap-y-16">
              {products.map((product) => (
                <div className="py-3 akayan transition-all duration-200 hover:bg-[#F9FAFB] px-4 max-w-[384px] flex space-x-4 items-start">
                  <img src={product.imgUrl} alt="" className="h-6 w-4" />
                  <div className="">
                    <div className="flex agoy items-center space-x-2">
                      <p className="text-black font-semibold">{product.name}</p>
                    </div>
                    <p className="text-gray font-normal text-sm mt-1">
                      {product.subtitle}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
        <img
          src="/home/Hero.png"
          className="absolute top-0 left-0 bottom-0 z-0"
        />
      </main>
    </>
  );
}
